/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjalistaapp.view;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

import penjalistaapp.model.Operater;

/**
 *
 * @author Josip
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    private Operater operater;
    Image image = Toolkit.getDefaultToolkit().getImage("Slike/climbingIcon.png");
    final TrayIcon icon = new TrayIcon(image, "Penjališta APP");
    private Date pocetakRada;
   
    public Izbornik(Operater operater) {
       
        initComponents();
        this.operater = operater;
        setTitle("Penjališta APP " + operater.getIme() + " " + operater.getPrezime());
         promjenaIzgleda();
         pocetakRada=new Date();

         definirajTimer();
         
 

        changeIcon();
        minimizeToSysTray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIzbornik = new javax.swing.JPanel();
        btnPenjaliste = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        btnPenjac = new javax.swing.JButton();
        btnGit = new javax.swing.JButton();
        btnEra = new javax.swing.JButton();
        lblSlika = new javax.swing.JLabel();
        lblVrijeme = new javax.swing.JLabel();
        jmbMenu = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        menImport = new javax.swing.JMenu();
        menExport = new javax.swing.JMenu();
        menHelp = new javax.swing.JMenu();
        jmiOAplikaciji = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Penjališta APP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        btnPenjaliste.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        btnPenjaliste.setText("Penjališta");
        btnPenjaliste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjalisteActionPerformed(evt);
            }
        });

        btnAutor.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        btnAutor.setText("Autori");
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        btnPenjac.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        btnPenjac.setText("Penjači");
        btnPenjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjacActionPerformed(evt);
            }
        });

        btnGit.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        btnGit.setText("GitHub");
        btnGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGitActionPerformed(evt);
            }
        });

        btnEra.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        btnEra.setText("ERA dijagram");
        btnEra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraActionPerformed(evt);
            }
        });

        lblSlika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjalistaapp/view/climber1.png"))); // NOI18N

        lblVrijeme.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        lblVrijeme.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlIzbornikLayout = new javax.swing.GroupLayout(pnlIzbornik);
        pnlIzbornik.setLayout(pnlIzbornikLayout);
        pnlIzbornikLayout.setHorizontalGroup(
            pnlIzbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzbornikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIzbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPenjac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPenjaliste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVrijeme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlIzbornikLayout.setVerticalGroup(
            pnlIzbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzbornikLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnPenjaliste)
                .addGap(18, 18, 18)
                .addComponent(btnAutor)
                .addGap(18, 18, 18)
                .addComponent(btnPenjac)
                .addGap(18, 18, 18)
                .addComponent(btnGit)
                .addGap(18, 18, 18)
                .addComponent(btnEra)
                .addGap(65, 65, 65)
                .addComponent(lblVrijeme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlIzbornikLayout.createSequentialGroup()
                .addComponent(lblSlika)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menFile.setText("File");

        jmiExit.setText("Zatvori");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        menFile.add(jmiExit);

        jmbMenu.add(menFile);

        menImport.setText("Import");
        jmbMenu.add(menImport);

        menExport.setText("Export");
        jmbMenu.add(menExport);

        menHelp.setText("Help");

        jmiOAplikaciji.setText("O aplikaciji");
        jmiOAplikaciji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOAplikacijiActionPerformed(evt);
            }
        });
        menHelp.add(jmiOAplikaciji);

        jmbMenu.add(menHelp);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlIzbornik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIzbornik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraActionPerformed
        Slika slika = new Slika();
        slika.setVisible(true);
    }//GEN-LAST:event_btnEraActionPerformed

    private void btnGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGitActionPerformed

        try {
            Desktop.getDesktop().browse(new URL("https://github.com/jkovacevic992/Penjalista-APP").toURI());
        } catch (URISyntaxException | IOException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnGitActionPerformed

    private void btnPenjalisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjalisteActionPerformed
        Penjalista penjaliste = new Penjalista();
        penjaliste.setVisible(true);
    }//GEN-LAST:event_btnPenjalisteActionPerformed

    private void btnPenjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjacActionPerformed
        Penjaci osoba = new Penjaci();
        osoba.setVisible(true);
    }//GEN-LAST:event_btnPenjacActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        Autori autor = new Autori();
        autor.setVisible(true);
    }//GEN-LAST:event_btnAutorActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        setVisible(false);
    }//GEN-LAST:event_formWindowIconified

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiOAplikacijiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOAplikacijiActionPerformed
        OAplikaciji oAplikaciji = new OAplikaciji();
        oAplikaciji.setVisible(true);
    }//GEN-LAST:event_jmiOAplikacijiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnEra;
    private javax.swing.JButton btnGit;
    private javax.swing.JButton btnPenjac;
    private javax.swing.JButton btnPenjaliste;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiOAplikaciji;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JLabel lblVrijeme;
    private javax.swing.JMenu menExport;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menHelp;
    private javax.swing.JMenu menImport;
    private javax.swing.JPanel pnlIzbornik;
    // End of variables declaration//GEN-END:variables

    private void minimizeToSysTray() {
     
         if (SystemTray.isSupported()) {
      SystemTray tray = SystemTray.getSystemTray();

      icon.setImageAutoSize(true);
      icon.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            setVisible(true);
            setExtendedState(JFrame.NORMAL);
            
         
         }
      });

      try {
        tray.add(icon);
      } catch (AWTException e) {
        System.err.println("Nije moguće dodati ikonu.");
      }
    }
            }

    private void changeIcon() {
               try {
    setIconImage(ImageIO.read(new File("Slike/climbingIcon.png")));
}
catch (IOException exc) {
    exc.printStackTrace();
}
    }

    private void promjenaIzgleda() {
        
        getContentPane().setBackground(Color.decode("#082F4E"));
        pnlIzbornik.setBackground(Color.decode("#082F4E"));
    }
            
    private void definirajTimer(){
         Timer timer = new Timer();
        timer.schedule(new  TimerTask() {
            @Override
            public void run() {
                
                long diffInSeconds = (new Date().getTime() - pocetakRada.getTime())/1000;
             

    long diff[] = new long[] { 0, 0, 0, 0 };
    /* sec */diff[3] = (diffInSeconds >= 60 ? diffInSeconds % 60 : diffInSeconds);
    /* min */diff[2] = (diffInSeconds = (diffInSeconds / 60)) >= 60 ? diffInSeconds % 60 : diffInSeconds;
    /* hours */diff[1] = (diffInSeconds = (diffInSeconds / 60)) >= 24 ? diffInSeconds % 24 : diffInSeconds;
    /* days */diff[0] = (diffInSeconds = (diffInSeconds / 24));

                lblVrijeme.setText(String.format(
        "%s%d:%s%d:%s%d",
        diff[1]<10 ? "0" : "",
        diff[1],
        diff[2]<10 ? "0" : "",
        diff[2],
        diff[3]<10 ? "0" : "",
        diff[3]));
            }
        }, 0, 1000);
    }
    }



    

