/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjalistaapp.view;

import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import penjalistaapp.model.Operater;
import penjalistaapp.pomocno.HibernateUtil;
import org.hibernate.Session;

/**
 *
 * @author Josip
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
         new SpojiSeNaBazu().start();
         changeIcon();
    }
    
    private class SpojiSeNaBazu extends Thread {

        public void run() {
            Session s = HibernateUtil.getSession();
           
            List<Operater> lista = s.createQuery("From Operater").list();
            Operater o = lista.isEmpty() ? null : lista.get(0);
            
                if (o!=null && o.getSifra() > 0) {
                    new Autorizacija().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "Greška, "
                            + "zovite proizvođača programa");
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjalistaapp/view/loading.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoading)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoading)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLoading;
    // End of variables declaration//GEN-END:variables

    private void changeIcon() {
               try {
    setIconImage(ImageIO.read(new File("Slike/climbingIcon.png")));
}
catch (IOException exc) {
    exc.printStackTrace();
}
    }


}
